#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-httpclient
Version  : 2.8.0
Release  : 6
URL      : https://rubygems.org/downloads/httpclient-2.8.0.gem
Source0  : https://rubygems.org/downloads/httpclient-2.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
Requires: rubygem-httpclient-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
httpclient - HTTP accessing library.  [![Gem Version](https://badge.fury.io/rb/httpclient.svg)](http://badge.fury.io/rb/httpclient)

%package bin
Summary: bin components for the rubygem-httpclient package.
Group: Binaries

%description bin
bin components for the rubygem-httpclient package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n httpclient-2.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-httpclient.gemspec

%build
gem build rubygem-httpclient.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
httpclient-2.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/httpclient-2.8.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/bin/httpclient
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/bin/jsonclient
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/hexdump.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/http-access2.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/http-access2/cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/http-access2/http.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/cacert.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/cacert1024.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/http.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/include_client.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/jruby_ssl_socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/ssl_config.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/ssl_socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/timeout.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/httpclient/webagent-cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/jsonclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/lib/oauthclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/async.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/dav.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/howto.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/jsonclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/oauth_buzz.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/oauth_friendfeed.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/oauth_twitter.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/0cert.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/0key.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/1000cert.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/1000key.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/htdocs/index.html
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/ssl_client.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/ssl/webrick_httpsd.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/thread.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/sample/wcat.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/ca-chain.pem
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/ca.cert
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/client-pass.key
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/client.cert
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/client.key
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/htdigest
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/htpasswd
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/server.cert
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/server.key
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/sslsvr.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/subca.cert
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_auth.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_hexdump.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_http-access2.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_httpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_include_client.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_jsonclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/httpclient-2.8.0/test/test_webagent-cookie.rb
/usr/lib64/ruby/gems/2.3.0/specifications/httpclient-2.8.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/httpclient
